.TH std::ios_base::failure 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   Defined in header <ios>
   class failure;

   The class std::ios_base::failure defines an exception object that is thrown on
   failure by the functions in the Input/Output library.

   std-ios base-failure-2003-inheritance.svg
   About this image                          \fI(until C++11)\fP

              Inheritance diagram
   std-ios base-failure-inheritance.svg
   About this image                          \fI(since C++11)\fP

              Inheritance diagram

.SH Contents

     * 1 Member functions
     * 2
       std::ios_base::failure::::failure

          * 2.1 Parameters
          * 2.2 Inherited from
            std::system_error

               * 2.2.1 Member functions

          * 2.3 Inherited from
            std::runtime_error
          * 2.4 Inherited from
            std::exception

               * 2.4.1 Member functions
               * 2.4.2 Example
               * 2.4.3 See also

.SH Member functions

   constructor   constructs the exception object
                 \fI(public member function)\fP

                            std::ios_base::failure::::failure

   explicit failure( const std::string& message );      \fI(until C++11)\fP
   explicit failure( const std::string& message,        \fI(since C++11)\fP
   const std::error_code& ec = std::io_errc::stream );
   explicit failure( const char* message,               \fI(since C++11)\fP
   const std::error_code& ec = std::io_errc::stream );

   Constructs the exception object using message as explanation string which can later
   be retrieved using what().

.SH Parameters

   message - explanatory string

Inherited from std::system_error

.SH Member functions

   code      returns error code
             \fI(public member function of std::system_error)\fP
   what      returns explanatory string
   \fB[virtual]\fP \fI(virtual public member function of std::system_error)\fP

Inherited from std::runtime_error

Inherited from std::exception

.SH Member functions

   destructor   destructs the exception object
   \fB[virtual]\fP    \fI(virtual public member function of std::exception)\fP
   what         returns an explanatory string
   \fB[virtual]\fP    \fI(virtual public member function of std::exception)\fP

.SH Example

   
// Run this code

 #include <iostream>
 #include <fstream>
 int main()
 {
     std::ifstream f("doesn't exist");
     try {
         f.exceptions(f.failbit);
     } catch (const std::ios_base::failure& e)
     {
         std::cout << "Caught an ios_base::failure.\\n"
                   << "Explanatory string: " << e.what() << '\\n'
                   << "Error code: " << e.code() << '\\n';
     }
 }

.SH Output:

 Caught an ios_base::failure.
 Explanatory string: ios_base::clear: unspecified iostream_category error
 Error code: iostream:1

.SH See also

   io_errc the IO stream error codes
   \fI(C++11)\fP \fI(enum)\fP
